In [25]:
import pandas as pd

In [26]:
df_population_data = pd.read_csv('C:/Users/thelsandro/Documents/GitHub/resumo_pandas_python/lojas.csv')

In [27]:
df_population_data

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [28]:
type(df_population_data)

pandas.core.frame.DataFrame

In [46]:
pd.set_option('display.max_rows',1115)

In [47]:
pd.set_option('display.max_columns',5)

In [48]:
df_population_data

      Store StoreType  ... Promo2SinceYear     PromoInterval
0         1         c  ...             NaN               NaN
1         2         a  ...          2010.0   Jan,Apr,Jul,Oct
2         3         a  ...          2011.0   Jan,Apr,Jul,Oct
3         4         c  ...             NaN               NaN
4         5         a  ...             NaN               NaN
5         6         a  ...             NaN               NaN
6         7         a  ...             NaN               NaN
7         8         a  ...             NaN               NaN
8         9         a  ...             NaN               NaN
9        10         a  ...             NaN               NaN
10       11         a  ...          2012.0   Jan,Apr,Jul,Oct
11       12         a  ...          2010.0   Jan,Apr,Jul,Oct
12       13         d  ...          2009.0   Feb,May,Aug,Nov
13       14         a  ...          2011.0   Jan,Apr,Jul,Oct
14       15         d  ...          2011.0   Jan,Apr,Jul,Oct
15       16         a  ...             NaN               NaN
16       17         a  ...          2010.0   Jan,Apr,Jul,Oct
17       18         d  ...          2012.0   Jan,Apr,Jul,Oct
18       19         a  ...          2011.0  Mar,Jun,Sept,Dec
19       20         d  ...          2014.0   Jan,Apr,Jul,Oct
20       21         c  ...          2009.0   Jan,Apr,Jul,Oct
21       22         a  ...          2012.0   Jan,Apr,Jul,Oct
22       23         d  ...             NaN               NaN
23       24         a  ...          2011.0   Jan,Apr,Jul,Oct
24       25         c  ...             NaN               NaN
25       26         d  ...             NaN               NaN
26       27         a  ...          2011.0   Jan,Apr,Jul,Oct
27       28         a  ...          2015.0  Mar,Jun,Sept,Dec
28       29         d  ...             NaN               NaN
29       30         a  ...          2014.0  Mar,Jun,Sept,Dec
30       31         d  ...             NaN               NaN
31       32         a  ...          2009.0   Feb,May,Aug,Nov
32       33         a  ...             NaN               NaN
33       34         c  ...             NaN               NaN
34       35         d  ...          2012.0   Jan,Apr,Jul,Oct
35       36         a  ...          2014.0   Jan,Apr,Jul,Oct
36       37         c  ...             NaN               NaN
37       38         d  ...             NaN               NaN
38       39         a  ...          2013.0   Feb,May,Aug,Nov
39       40         a  ...          2009.0   Feb,May,Aug,Nov
40       41         d  ...          2013.0   Jan,Apr,Jul,Oct
41       42         a  ...          2011.0   Jan,Apr,Jul,Oct
42       43         d  ...          2009.0   Jan,Apr,Jul,Oct
43       44         a  ...             NaN               NaN
44       45         d  ...             NaN               NaN
45       46         c  ...          2011.0   Jan,Apr,Jul,Oct
46       47         a  ...          2013.0   Jan,Apr,Jul,Oct
47       48         a  ...             NaN               NaN
48       49         d  ...             NaN               NaN
49       50         d  ...             NaN               NaN
50       51         a  ...          2011.0   Jan,Apr,Jul,Oct
51       52         d  ...          2010.0   Jan,Apr,Jul,Oct
52       53         a  ...             NaN               NaN
53       54         d  ...          2013.0   Feb,May,Aug,Nov
54       55         a  ...             NaN               NaN
55       56         d  ...          2014.0  Mar,Jun,Sept,Dec
56       57         d  ...             NaN               NaN
57       58         a  ...          2012.0   Jan,Apr,Jul,Oct
58       59         a  ...          2011.0   Jan,Apr,Jul,Oct
59       60         d  ...             NaN               NaN
60       61         a  ...          2012.0   Jan,Apr,Jul,Oct
61       62         a  ...             NaN               NaN
62       63         c  ...          2010.0   Feb,May,Aug,Nov
63       64         d  ...          2013.0   Jan,Apr,Jul,Oct
64       65         a  ...          2012.0   Jan,Apr,Jul,Oct
65       66         d  ...          2009.0   Jan,Apr,Jul,Oct
66       67         a  ...             NaN               NaN
67       68         a  ...          2012.0  Mar,Jun,Sept,Dec
68       69         c  ...          2011.0   Jan,Apr,Jul,Oct
69       70         c  ...             NaN               NaN
70       71         a  ...          2009.0  Mar,Jun,Sept,Dec
71       72         a  ...          2010.0   Jan,Apr,Jul,Oct
72       73         a  ...             NaN               NaN
73       74         a  ...             NaN               NaN
74       75         d  ...             NaN               NaN
75       76         d  ...             NaN               NaN
76       77         d  ...          2014.0   Jan,Apr,Jul,Oct
77       78         a  ...          2013.0   Feb,May,Aug,Nov
78       79         a  ...             NaN               NaN
79       80         d  ...             NaN               NaN
80       81         a  ...          2014.0   Jan,Apr,Jul,Oct
81       82         a  ...          2009.0   Jan,Apr,Jul,Oct
82       83         a  ...             NaN               NaN
83       84         a  ...             NaN               NaN
84       85         b  ...             NaN               NaN
85       86         a  ...          2013.0   Jan,Apr,Jul,Oct
86       87         a  ...             NaN               NaN
87       88         a  ...             NaN               NaN
88       89         a  ...          2014.0   Jan,Apr,Jul,Oct
89       90         a  ...             NaN               NaN
90       91         c  ...          2011.0   Jan,Apr,Jul,Oct
91       92         c  ...          2009.0   Feb,May,Aug,Nov
92       93         a  ...          2011.0   Jan,Apr,Jul,Oct
93       94         d  ...             NaN               NaN
94       95         a  ...             NaN               NaN
95       96         a  ...          2009.0   Jan,Apr,Jul,Oct
96       97         d  ...             NaN               NaN
97       98         d  ...          2012.0   Jan,Apr,Jul,Oct
98       99         c  ...          2012.0  Mar,Jun,Sept,Dec
99      100         d  ...             NaN               NaN
100     101         d  ...          2012.0  Mar,Jun,Sept,Dec
101     102         a  ...          2014.0  Mar,Jun,Sept,Dec
102     103         d  ...             NaN               NaN
103     104         a  ...             NaN               NaN
104     105         a  ...          2013.0  Mar,Jun,Sept,Dec
105     106         a  ...             NaN               NaN
106     107         a  ...             NaN               NaN
107     108         d  ...             NaN               NaN
108     109         a  ...             NaN               NaN
109     110         a  ...             NaN               NaN
110     111         d  ...          2009.0   Jan,Apr,Jul,Oct
111     112         a  ...             NaN               NaN
112     113         d  ...             NaN               NaN
113     114         c  ...          2011.0  Mar,Jun,Sept,Dec
114     115         d  ...          2014.0   Jan,Apr,Jul,Oct
115     116         a  ...             NaN               NaN
116     117         a  ...             NaN               NaN
117     118         d  ...             NaN               NaN
118     119         a  ...             NaN               NaN
119     120         d  ...          2009.0   Jan,Apr,Jul,Oct
120     121         a  ...          2013.0  Mar,Jun,Sept,Dec
121     122         a  ...             NaN               NaN
122     123         a  ...             NaN               NaN
123     124         a  ...             NaN               NaN
124     125         a  ...             NaN               NaN
125     126         d  ...          2011.0   Feb,May,Aug,Nov
126     127         d  ...          2010.0   Jan,Apr,Jul,Oct
127     128         d  ...          2013.0   Jan,Apr,Jul,Oct
128     129         a  ...          2011.0   Jan,Apr,Jul,Oct
129     130         c  ...          2010.0   Jan,Apr,Jul,Oct
130     131         c  ...             NaN               NaN
131     132         d  ...          2012.0   Jan,Apr,Jul,Oct
132     133         a  ...          2014.0  Mar,Jun,Sept,Dec
133     134         a  ...             NaN               NaN
134     135         d  ...          2013.0   Jan,Apr,Jul,Oct
135     136         a  ...          2012.0   Feb,May,Aug,Nov
136     137         a  ...          2014.0   Jan,Apr,Jul,Oct
137     138         a  ...             NaN               NaN
138     139         a  ...          2011.0   Jan,Apr,Jul,Oct
139     140         a  ...          2013.0   Jan,Apr,Jul,Oct
140     141         c  ...          2012.0  Mar,Jun,Sept,Dec
141     142         a  ...             NaN               NaN
142     143         d  ...             NaN               NaN
143     144         a  ...             NaN               NaN
144     145         a  ...          2009.0   Feb,May,Aug,Nov
145     146         d  ...          2012.0   Jan,Apr,Jul,Oct
146     147         d  ...             NaN               NaN
147     148         a  ...             NaN               NaN
148     149         d  ...          2011.0   Jan,Apr,Jul,Oct
149     150         c  ...             NaN               NaN
150     151         d  ...             NaN               NaN
151     152         a  ...             NaN               NaN
152     153         a  ...          2011.0   Feb,May,Aug,Nov
153     154         d  ...             NaN               NaN
154     155         d  ...          2010.0   Jan,Apr,Jul,Oct
155     156         a  ...          2011.0  Mar,Jun,Sept,Dec
156     157         a  ...             NaN               NaN
157     158         d  ...          2009.0   Feb,May,Aug,Nov
158     159         d  ...             NaN               NaN
159     160         d  ...             NaN               NaN
160     161         a  ...             NaN               NaN
161     162         d  ...          2010.0   Jan,Apr,Jul,Oct
162     163         a  ...             NaN               NaN
163     164         a  ...          2010.0   Jan,Apr,Jul,Oct
164     165         a  ...          2010.0   Jan,Apr,Jul,Oct
165     166         a  ...          2013.0   Jan,Apr,Jul,Oct
166     167         a  ...             NaN               NaN
167     168         a  ...             NaN               NaN
168     169         d  ...          2014.0   Feb,May,Aug,Nov
169     170         a  ...          2011.0   Jan,Apr,Jul,Oct
170     171         a  ...             NaN               NaN
171     172         a  ...          2014.0   Jan,Apr,Jul,Oct
172     173         a  ...             NaN               NaN
173     174         a  ...          2012.0   Jan,Apr,Jul,Oct
174     175         c  ...             NaN               NaN
175     176         a  ...             NaN               NaN
176     177         a  ...          2013.0   Feb,May,Aug,Nov
177     178         d  ...             NaN               NaN
178     179         a  ...             NaN               NaN
179     180         d  ...             NaN               NaN
180     181         a  ...          2011.0   Jan,Apr,Jul,Oct
181     182         d  ...          2011.0  Mar,Jun,Sept,Dec
182     183         a  ...             NaN               NaN
183     184         d  ...             NaN               NaN
184     185         d  ...             NaN               NaN
185     186         a  ...          2014.0   Jan,Apr,Jul,Oct
186     187         a  ...             NaN               NaN
187     188         d  ...          2011.0   Feb,May,Aug,Nov
188     189         d  ...             NaN               NaN
189     190         a  ...          2014.0   Jan,Apr,Jul,Oct
190     191         a  ...          2014.0   Jan,Apr,Jul,Oct
191     192         d  ...          2014.0   Jan,Apr,Jul,Oct
192     193         a  ...             NaN               NaN
193     194         d  ...          2013.0   Feb,May,Aug,Nov
194     195         a  ...             NaN               NaN
195     196         c  ...          2011.0   Jan,Apr,Jul,Oct
196     197         c  ...             NaN               NaN
197     198         a  ...          2010.0   Jan,Apr,Jul,Oct
198     199         d  ...          2012.0  Mar,Jun,Sept,Dec
199     200         a  ...             NaN               NaN
200     201         d  ...          2014.0  Mar,Jun,Sept,Dec
201     202         d  ...             NaN               NaN
202     203         c  ...             NaN               NaN
203     204         a  ...          2014.0   Jan,Apr,Jul,Oct
204     205         a  ...             NaN               NaN
205     206         a  ...          2012.0   Jan,Apr,Jul,Oct
206     207         a  ...             NaN               NaN
207     208         c  ...             NaN               NaN
208     209         a  ...          2013.0   Jan,Apr,Jul,Oct
209     210         d  ...          2013.0   Feb,May,Aug,Nov
210     211         a  ...             NaN               NaN
211     212         a  ...             NaN               NaN
212     213         d  ...          2014.0   Jan,Apr,Jul,Oct
213     214         d  ...          2014.0   Jan,Apr,Jul,Oct
214     215         d  ...          2009.0   Feb,May,Aug,Nov
215     216         c  ...          2009.0   Feb,May,Aug,Nov
216     217         c  ...             NaN               NaN
217     218         a  ...          2011.0  Mar,Jun,Sept,Dec
218     219         a  ...             NaN               NaN
219     220         a  ...             NaN               NaN
220     221         d  ...             NaN               NaN
221     222         a  ...             NaN               NaN
222     223         d  ...          2011.0   Jan,Apr,Jul,Oct
223     224         d  ...          2013.0   Jan,Apr,Jul,Oct
224     225         d  ...             NaN               NaN
225     226         a  ...             NaN               NaN
226     227         a  ...             NaN               NaN
227     228         d  ...          2011.0   Feb,May,Aug,Nov
228     229         d  ...          2011.0   Jan,Apr,Jul,Oct
229     230         d  ...             NaN               NaN
230     231         d  ...          2010.0   Feb,May,Aug,Nov
231     232         c  ...          2013.0  Mar,Jun,Sept,Dec
232     233         a  ...             NaN               NaN
233     234         d  ...             NaN               NaN
234     235         a  ...          2009.0   Jan,Apr,Jul,Oct
235     236         a  ...             NaN               NaN
236     237         a  ...             NaN               NaN
237     238         a  ...          2009.0   Feb,May,Aug,Nov
238     239         d  ...             NaN               NaN
239     240         a  ...             NaN               NaN
240     241         d  ...             NaN               NaN
241     242         d  ...          2011.0   Jan,Apr,Jul,Oct
242     243         a  ...          2013.0   Feb,May,Aug,Nov
243     244         d  ...          2012.0   Jan,Apr,Jul,Oct
244     245         a  ...             NaN               NaN
245     246         c  ...             NaN               NaN
246     247         d  ...          2013.0   Feb,May,Aug,Nov
247     248         a  ...          2012.0   Jan,Apr,Jul,Oct
248     249         d  ...             NaN               NaN
249     250         d  ...          2012.0   Feb,May,Aug,Nov
250     251         a  ...             NaN               NaN
251     252         d  ...          2010.0   Feb,May,Aug,Nov
252     253         a  ...          2013.0   Feb,May,Aug,Nov
253     254         d  ...          2012.0  Mar,Jun,Sept,Dec
254     255         c  ...          2011.0   Feb,May,Aug,Nov
255     256         a  ...          2014.0  Mar,Jun,Sept,Dec
256     257         a  ...             NaN               NaN
257     258         a  ...          2009.0   Jan,Apr,Jul,Oct
258     259         b  ...             NaN               NaN
259     260         a  ...             NaN               NaN
260     261         d  ...          2009.0   Jan,Apr,Jul,Oct
261     262         b  ...             NaN               NaN
262     263         a  ...          2014.0   Jan,Apr,Jul,Oct
263     264         a  ...             NaN               NaN
264     265         a  ...          2015.0   Jan,Apr,Jul,Oct
265     266         a  ...          2011.0  Mar,Jun,Sept,Dec
266     267         c  ...             NaN               NaN
267     268         a  ...             NaN               NaN
268     269         a  ...             NaN               NaN
269     270         a  ...             NaN               NaN
270     271         a  ...          2011.0   Jan,Apr,Jul,Oct
271     272         a  ...          2011.0   Jan,Apr,Jul,Oct
272     273         a  ...             NaN               NaN
273     274         b  ...          2013.0   Jan,Apr,Jul,Oct
274     275         d  ...          2014.0   Jan,Apr,Jul,Oct
275     276         a  ...          2013.0  Mar,Jun,Sept,Dec
276     277         d  ...          2009.0   Feb,May,Aug,Nov
277     278         a  ...             NaN               NaN
278     279         d  ...          2012.0   Jan,Apr,Jul,Oct
279     280         d  ...          2014.0  Mar,Jun,Sept,Dec
280     281         d  ...             NaN               NaN
281     282         a  ...             NaN               NaN
282     283         a  ...          2014.0   Jan,Apr,Jul,Oct
283     284         d  ...          2014.0   Jan,Apr,Jul,Oct
284     285         a  ...             NaN               NaN
285     286         a  ...             NaN               NaN
286     287         c  ...          2014.0   Jan,Apr,Jul,Oct
287     288         d  ...          2011.0  Mar,Jun,Sept,Dec
288     289         d  ...             NaN               NaN
289     290         a  ...             NaN               NaN
290     291         d  ...             NaN               NaN
291     292         a  ...             NaN               NaN
292     293         c  ...             NaN               NaN
293     294         a  ...             NaN               NaN
294     295         a  ...          2013.0  Mar,Jun,Sept,Dec
295     296         a  ...          2014.0   Feb,May,Aug,Nov
296     297         a  ...             NaN               NaN
297     298         d  ...             NaN               NaN
298     299         d  ...             NaN               NaN
299     300         a  ...          2012.0   Jan,Apr,Jul,Oct
300     301         a  ...             NaN               NaN
301     302         d  ...          2011.0  Mar,Jun,Sept,Dec
302     303         a  ...          2011.0   Feb,May,Aug,Nov
303     304         a  ...             NaN               NaN
304     305         c  ...          2013.0  Mar,Jun,Sept,Dec
305     306         a  ...          2014.0   Jan,Apr,Jul,Oct
306     307         a  ...             NaN               NaN
307     308         a  ...          2010.0   Jan,Apr,Jul,Oct
308     309         d  ...          2009.0   Feb,May,Aug,Nov
309     310         a  ...          2014.0  Mar,Jun,Sept,Dec
310     311         a  ...             NaN               NaN
311     312         d  ...             NaN               NaN
312     313         d  ...             NaN               NaN
313     314         a  ...          2013.0   Feb,May,Aug,Nov
314     315         a  ...             NaN               NaN
315     316         d  ...             NaN               NaN
316     317         d  ...          2011.0   Jan,Apr,Jul,Oct
317     318         d  ...             NaN               NaN
318     319         a  ...          2012.0  Mar,Jun,Sept,Dec
319     320         a  ...             NaN               NaN
320     321         c  ...          2014.0  Mar,Jun,Sept,Dec
321     322         a  ...          2009.0   Jan,Apr,Jul,Oct
322     323         d  ...          2013.0   Feb,May,Aug,Nov
323     324         a  ...          2011.0   Jan,Apr,Jul,Oct
324     325         a  ...          2011.0   Feb,May,Aug,Nov
325     326         d  ...          2013.0   Feb,May,Aug,Nov

In [49]:
pd.reset_option('display.max_columns')

In [50]:
df_population_data

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN
10,11,a,c,960.0,11.0,2011.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
11,12,a,c,1070.0,NaN,NaN,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
12,13,d,a,310.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
13,14,a,a,1300.0,3.0,2014.0,1,40.0,2011.0,"Jan,Apr,Jul,Oct"
14,15,d,c,4110.0,3.0,2010.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
15,16,a,c,3270.0,NaN,NaN,0,NaN,NaN,NaN
16,17,a,a,50.0,12.0,2005.0,1,26.0,2010.0,"Jan,Apr,Jul,Oct"
17,18,d,c,13840.0,6.0,2010.0,1,14.0,2012.0,"Jan,Apr,Jul,Oct"
18,19,a,c,3240.0,NaN,NaN,1,22.0,2011.0,"Mar,Jun,Sept,Dec"
19,20,d,a,2340.0,5.0,2009.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
20,21,c,c,550.0,10.0,1999.0,1,45.0,2009.0,"Jan,Apr,Jul,Oct"
21,22,a,a,1040.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
22,23,d,a,4060.0,8.0,2005.0,0,NaN,NaN,NaN
23,24,a,c,4590.0,3.0,2000.0,1,40.0,2011.0,"Jan,Apr,Jul,Oct"
24,25,c,a,430.0,4.0,2003.0,0,NaN,NaN,NaN
25,26,d,a,2300.0,NaN,NaN,0,NaN,NaN,NaN
26,27,a,a,60.0,1.0,2005.0,1,5.0,2011.0,"Jan,Apr,Jul,Oct"
27,28,a,a,1200.0,10.0,2014.0,1,6.0,2015.0,"Mar,Jun,Sept,Dec"
28,29,d,c,2170.0,NaN,NaN,0,NaN,NaN,NaN
29,30,a,a,40.0,2.0,2014.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
30,31,d,c,9800.0,7.0,2012.0,0,NaN,NaN,NaN
31,32,a,a,2910.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
32,33,a,c,1320.0,5.0,2013.0,0,NaN,NaN,NaN
33,34,c,a,2240.0,9.0,2009.0,0,NaN,NaN,NaN
34,35,d,c,7660.0,10.0,2000.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
35,36,a,c,540.0,6.0,2003.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
36,37,c,a,4230.0,12.0,2014.0,0,NaN,NaN,NaN
37,38,d,a,1090.0,4.0,2007.0,0,NaN,NaN,NaN
38,39,a,a,260.0,10.0,2006.0,1,31.0,2013.0,"Feb,May,Aug,Nov"
39,40,a,a,180.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
40,41,d,c,1180.0,NaN,NaN,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
41,42,a,c,290.0,NaN,NaN,1,40.0,2011.0,"Jan,Apr,Jul,Oct"
42,43,d,a,4880.0,NaN,NaN,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
43,44,a,a,540.0,6.0,2011.0,0,NaN,NaN,NaN
44,45,d,a,9710.0,2.0,2014.0,0,NaN,NaN,NaN
45,46,c,a,1200.0,9.0,2005.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
46,47,a,c,270.0,4.0,2013.0,1,14.0,2013.0,"Jan,Apr,Jul,Oct"
47,48,a,a,1060.0,5.0,2012.0,0,NaN,NaN,NaN
48,49,d,c,18010.0,9.0,2007.0,0,NaN,NaN,NaN
49,50,d,a,6260.0,11.0,2009.0,0,NaN,NaN,NaN
50,51,a,c,10570.0,7.0,2013.0,1,9.0,2011.0,"Jan,Apr,Jul,Oct"
51,52,d,c,450.0,4.0,2014.0,1,39.0,2010.0,"Jan,Apr,Jul,Oct"
52,53,a,c,30360.0,9.0,2013.0,0,NaN,NaN,NaN
53,54,d,c,7170.0,8.0,2014.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
54,55,a,a,720.0,11.0,2004.0,0,NaN,NaN,NaN
55,56,d,c,6620.0,3.0,2012.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
56,57,d,c,420.0,6.0,2014.0,0,NaN,NaN,NaN
57,58,a,c,7340.0,5.0,2008.0,1,27.0,2012.0,"Jan,Apr,Jul,Oct"
58,59,a,c,2840.0,6.0,2007.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
59,60,d,c,5540.0,10.0,2009.0,0,NaN,NaN,NaN
60,61,a,c,350.0,12.0,2007.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
61,62,a,a,2050.0,NaN,NaN,0,NaN,NaN,NaN
62,63,c,c,3700.0,6.0,2010.0,1,18.0,2010.0,"Feb,May,Aug,Nov"
63,64,d,c,22560.0,NaN,NaN,1,14.0,2013.0,"Jan,Apr,Jul,Oct"
64,65,a,c,13840.0,5.0,2010.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
65,66,d,a,7660.0,NaN,NaN,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
66,67,a,c,410.0,2.0,2006.0,0,NaN,NaN,NaN
67,68,a,c,250.0,NaN,NaN,1,35.0,2012.0,"Mar,Jun,Sept,Dec"
68,69,c,c,1130.0,NaN,NaN,1,40.0,2011.0,"Jan,Apr,Jul,Oct"
69,70,c,c,4840.0,NaN,NaN,0,NaN,NaN,NaN
70,71,a,a,17500.0,8.0,2008.0,1,37.0,2009.0,"Mar,Jun,Sept,Dec"
71,72,a,a,2200.0,12.0,2009.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
72,73,a,c,1650.0,9.0,2008.0,0,NaN,NaN,NaN
73,74,a,a,330.0,NaN,NaN,0,NaN,NaN,NaN
74,75,d,c,22440.0,12.0,2013.0,0,NaN,NaN,NaN
75,76,d,c,19960.0,3.0,2006.0,0,NaN,NaN,NaN
76,77,d,c,1090.0,8.0,2009.0,1,10.0,2014.0,"Jan,Apr,Jul,Oct"
77,78,a,a,3510.0,11.0,2006.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
78,79,a,a,3320.0,NaN,NaN,0,NaN,NaN,NaN
79,80,d,a,7910.0,NaN,NaN,0,NaN,NaN,NaN
80,81,a,a,2370.0,3.0,2011.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
81,82,a,a,22390.0,4.0,2008.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
82,83,a,a,2710.0,NaN,NaN,0,NaN,NaN,NaN
83,84,a,c,11810.0,8.0,2014.0,0,NaN,NaN,NaN
84,85,b,a,1870.0,10.0,2011.0,0,NaN,NaN,NaN
85,86,a,a,480.0,2.0,2005.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
86,87,a,a,560.0,12.0,2010.0,0,NaN,NaN,NaN
87,88,a,a,10690.0,10.0,2005.0,0,NaN,NaN,NaN
88,89,a,a,2380.0,7.0,2004.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
89,90,a,a,330.0,11.0,2007.0,0,NaN,NaN,NaN
90,91,c,a,2410.0,NaN,NaN,1,35.0,2011.0,"Jan,Apr,Jul,Oct"
91,92,c,a,240.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
92,93,a,a,16690.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
93,94,d,c,14620.0,NaN,NaN,0,NaN,NaN,NaN
94,95,a,a,1890.0,10.0,2014.0,0,NaN,NaN,NaN
95,96,a,a,8780.0,2.0,2005.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
96,97,d,c,8980.0,NaN,NaN,0,NaN,NaN,NaN
97,98,d,c,15140.0,12.0,2006.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
98,99,c,c,2030.0,11.0,2003.0,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
99,100,d,a,17930.0,NaN,NaN,0,NaN,NaN,NaN
100,101,d,c,2440.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
101,102,a,a,150.0,12.0,2007.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
102,103,d,c,5210.0,5.0,2015.0,0,NaN,NaN,NaN
103,104,a,a,390.0,6.0,2009.0,0,NaN,NaN,NaN
104,105,a,c,6190.0,NaN,NaN,1,23.0,2013.0,"Mar,Jun,Sept,Dec"
105,106,a,a,1390.0,8.0,2013.0,0,NaN,NaN,NaN
106,107,a,a,1930.0,9.0,2009.0,0,NaN,NaN,NaN
107,108,d,c,2190.0,9.0,2003.0,0,NaN,NaN,NaN
108,109,a,c,3300.0,11.0,2010.0,0,NaN,NaN,NaN
109,110,a,c,46590.0,4.0,2013.0,0,NaN,NaN,NaN
110,111,d,c,7890.0,NaN,NaN,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
111,112,a,a,1630.0,9.0,2009.0,0,NaN,NaN,NaN
112,113,d,c,20930.0,11.0,1999.0,0,NaN,NaN,NaN
113,114,c,a,4510.0,NaN,NaN,1,48.0,2011.0,"Mar,Jun,Sept,Dec"
114,115,d,c,5740.0,4.0,2007.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
115,116,a,a,680.0,4.0,2013.0,0,NaN,NaN,NaN
116,117,a,a,3450.0,9.0,2011.0,0,NaN,NaN,NaN
117,118,d,c,3580.0,9.0,2012.0,0,NaN,NaN,NaN
118,119,a,c,2100.0,2.0,2010.0,0,NaN,NaN,NaN
119,120,d,a,2290.0,12.0,2014.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
120,121,a,a,3570.0,11.0,2009.0,1,36.0,2013.0,"Mar,Jun,Sept,Dec"
121,122,a,c,58260.0,4.0,2013.0,0,NaN,NaN,NaN
122,123,a,a,16760.0,9.0,2011.0,0,NaN,NaN,NaN
123,124,a,a,1410.0,4.0,2003.0,0,NaN,NaN,NaN
124,125,a,a,760.0,12.0,2005.0,0,NaN,NaN,NaN
125,126,d,a,3370.0,10.0,2014.0,1,18.0,2011.0,"Feb,May,Aug,Nov"
126,127,d,a,1350.0,12.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
127,128,d,c,2000.0,NaN,NaN,1,1.0,2013.0,"Jan,Apr,Jul,Oct"
128,129,a,a,2460.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
129,130,c,a,900.0,NaN,NaN,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
130,131,c,a,920.0,7.0,2015.0,0,NaN,NaN,NaN
131,132,d,c,1040.0,NaN,NaN,1,27.0,2012.0,"Jan,Apr,Jul,Oct"
132,133,a,a,270.0,8.0,2013.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
133,134,a,a,1200.0,9.0,2008.0,0,NaN,NaN,NaN
134,135,d,a,5190.0,NaN,NaN,1,1.0,2013.0,"Jan,Apr,Jul,Oct"
135,136,a,c,2200.0,12.0,2010.0,1,22.0,2012.0,"Feb,May,Aug,Nov"
136,137,a,a,1730.0,7.0,2015.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
137,138,a,c,25360.0,10.0,2014.0,0,NaN,NaN,NaN
138,139,a,a,1700.0,1.0,2008.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
139,140,a,c,1090.0,7.0,2010.0,1,1.0,2013.0,"Jan,Apr,Jul,Oct"
140,141,c,c,1540.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
141,142,a,a,1090.0,7.0,2002.0,0,NaN,NaN,NaN
142,143,d,a,2930.0,12.0,2002.0,0,NaN,NaN,NaN
143,144,a,c,16570.0,NaN,NaN,0,NaN,NaN,NaN
144,145,a,a,280.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
145,146,d,c,8050.0,10.0,1961.0,1,48.0,2012.0,"Jan,Apr,Jul,Oct"
146,147,d,c,8540.0,NaN,NaN,0,NaN,NaN,NaN
147,148,a,a,2090.0,12.0,2008.0,0,NaN,NaN,NaN
148,149,d,a,2610.0,7.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
149,150,c,c,31830.0,3.0,2010.0,0,NaN,NaN,NaN
150,151,d,c,4360.0,10.0,2005.0,0,NaN,NaN,NaN
151,152,a,a,1780.0,NaN,NaN,0,NaN,NaN,NaN
152,153,a,a,16240.0,10.0,2000.0,1,18.0,2011.0,"Feb,May,Aug,Nov"
153,154,d,c,16420.0,NaN,NaN,0,NaN,NaN,NaN
154,155,d,a,3050.0,NaN,NaN,1,35.0,2010.0,"Jan,Apr,Jul,Oct"
155,156,a,a,2020.0,2.0,2011.0,1,14.0,2011.0,"Mar,Jun,Sept,Dec"
156,157,a,c,2950.0,10.0,2004.0,0,NaN,NaN,NaN
157,158,d,c,11840.0,NaN,NaN,1,31.0,2009.0,"Feb,May,Aug,Nov"
158,159,d,a,8530.0,3.0,2013.0,0,NaN,NaN,NaN
159,160,d,c,17110.0,11.0,2005.0,0,NaN,NaN,NaN
160,161,a,c,2970.0,3.0,2005.0,0,NaN,NaN,NaN
161,162,d,c,5340.0,3.0,2012.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
162,163,a,a,1480.0,4.0,2009.0,0,NaN,NaN,NaN
163,164,a,a,1160.0,9.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
164,165,a,a,3720.0,4.0,2005.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
165,166,a,c,100.0,4.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
166,167,a,a,140.0,4.0,2008.0,0,NaN,NaN,NaN
167,168,a,a,12540.0,NaN,NaN,0,NaN,NaN,NaN
168,169,d,a,980.0,7.0,2014.0,1,18.0,2014.0,"Feb,May,Aug,Nov"
169,170,a,a,1070.0,5.0,2015.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
170,171,a,a,2640.0,NaN,NaN,0,NaN,NaN,NaN
171,172,a,a,110.0,NaN,NaN,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
172,173,a,a,350.0,12.0,2012.0,0,NaN,NaN,NaN
173,174,a,a,13090.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
174,175,c,a,4130.0,NaN,NaN,0,NaN,NaN,NaN
175,176,a,a,3770.0,NaN,NaN,0,NaN,NaN,NaN
176,177,a,a,1250.0,2.0,2004.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
177,178,d,a,1710.0,NaN,NaN,0,NaN,NaN,NaN
178,179,a,c,480.0,NaN,NaN,0,NaN,NaN,NaN
179,180,d,a,5800.0,9.0,2010.0,0,NaN,NaN,NaN
180,181,a,a,12610.0,3.0,2013.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
181,182,d,c,1390.0,NaN,NaN,1,9.0,2011.0,"Mar,Jun,Sept,Dec"
182,183,a,a,9670.0,NaN,NaN,0,NaN,NaN,NaN
183,184,d,c,3560.0,NaN,NaN,0,NaN,NaN,NaN
184,185,d,c,1860.0,5.0,2015.0,0,NaN,NaN,NaN
185,186,a,a,290.0,10.0,2011.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
186,187,a,c,19360.0,NaN,NaN,0,NaN,NaN,NaN
187,188,d,a,850.0,NaN,NaN,1,18.0,2011.0,"Feb,May,Aug,Nov"
188,189,d,a,5760.0,7.0,2014.0,0,NaN,NaN,NaN
189,190,a,a,1470.0,12.0,2006.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
190,191,a,a,1100.0,8.0,2013.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
191,192,d,c,2770.0,3.0,2008.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
192,193,a,a,520.0,NaN,NaN,0,NaN,NaN,NaN
193,194,d,c,16970.0,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"
194,195,a,c,220.0,NaN,NaN,0,NaN,NaN,NaN
195,196,c,a,3850.0,11.0,2005.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
196,197,c,a,4210.0,3.0,2015.0,0,NaN,NaN,NaN
197,198,a,a,290.0,9.0,2002.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
198,199,d,c,6360.0,12.0,2010.0,1,14.0,2012.0,"Mar,Jun,Sept,Dec"
199,200,a,a,1650.0,10.0,2000.0,0,NaN,NaN,NaN
200,201,d,a,20260.0,NaN,NaN,1,18.0,2014.0,"Mar,Jun,Sept,Dec"
201,202,d,c,5140.0,5.0,2010.0,0,NaN,NaN,NaN
202,203,c,c,490.0,11.0,2002.0,0,NaN,NaN,NaN
203,204,a,a,5630.0,12.0,2002.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
204,205,a,a,110.0,12.0,2007.0,0,NaN,NaN,NaN
205,206,a,c,380.0,NaN,NaN,1,14.0,2012.0,"Jan,Apr,Jul,Oct"
206,207,a,a,6870.0,NaN,NaN,0,NaN,NaN,NaN
207,208,c,a,300.0,4.0,2006.0,0,NaN,NaN,NaN
208,209,a,c,11680.0,9.0,2011.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
209,210,d,a,970.0,11.0,1999.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
210,211,a,c,350.0,11.0,2006.0,0,NaN,NaN,NaN
211,212,a,c,15050.0,9.0,2008.0,0,NaN,NaN,NaN
212,213,d,c,4030.0,3.0,2014.0,1,1.0,2014.0,"Jan,Apr,Jul,Oct"
213,214,d,a,8650.0,7.0,2013.0,1,10.0,2014.0,"Jan,Apr,Jul,Oct"
214,215,d,a,150.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
215,216,c,a,190.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
216,217,c,a,3150.0,NaN,NaN,0,NaN,NaN,NaN
217,218,a,c,640.0,NaN,NaN,1,9.0,2011.0,"Mar,Jun,Sept,Dec"
218,219,a,a,1640.0,2.0,2013.0,0,NaN,NaN,NaN
219,220,a,a,1000.0,9.0,2008.0,0,NaN,NaN,NaN
220,221,d,c,13530.0,9.0,2013.0,0,NaN,NaN,NaN
221,222,a,a,2170.0,11.0,2008.0,0,NaN,NaN,NaN
222,223,d,c,2920.0,10.0,1995.0,1,27.0,2011.0,"Jan,Apr,Jul,Oct"
223,224,d,c,7930.0,NaN,NaN,1,1.0,2013.0,"Jan,Apr,Jul,Oct"
224,225,d,a,10180.0,5.0,2015.0,0,NaN,NaN,NaN
225,226,a,a,450.0,NaN,NaN,0,NaN,NaN,NaN
226,227,a,a,2370.0,NaN,NaN,0,NaN,NaN,NaN
227,228,d,c,10800.0,NaN,NaN,1,18.0,2011.0,"Feb,May,Aug,Nov"
228,229,d,c,17410.0,4.0,2007.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
229,230,d,c,6680.0,9.0,2013.0,0,NaN,NaN,NaN
230,231,d,c,3840.0,10.0,2008.0,1,39.0,2010.0,"Feb,May,Aug,Nov"
231,232,c,c,13570.0,5.0,2010.0,1,10.0,2013.0,"Mar,Jun,Sept,Dec"
232,233,a,a,1890.0,NaN,NaN,0,NaN,NaN,NaN
233,234,d,a,4370.0,NaN,NaN,0,NaN,NaN,NaN
234,235,a,a,5710.0,3.0,2012.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
235,236,a,a,1000.0,11.0,2007.0,0,NaN,NaN,NaN
236,237,a,a,1420.0,11.0,2007.0,0,NaN,NaN,NaN
237,238,a,a,320.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
238,239,d,c,610.0,NaN,NaN,0,NaN,NaN,NaN
239,240,a,a,1110.0,5.0,2009.0,0,NaN,NaN,NaN
240,241,d,c,780.0,NaN,NaN,0,NaN,NaN,NaN
241,242,d,a,6880.0,9.0,2001.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
242,243,a,a,310.0,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"
243,244,d,a,710.0,3.0,2012.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
244,245,a,c,1310.0,NaN,NaN,0,NaN,NaN,NaN
245,246,c,a,4660.0,4.0,2013.0,0,NaN,NaN,NaN
246,247,d,c,70.0,11.0,2010.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
247,248,a,c,340.0,9.0,2012.0,1,40.0,2012.0,"Jan,Apr,Jul,Oct"
248,249,d,c,18010.0,9.0,2014.0,0,NaN,NaN,NaN
249,250,d,a,3520.0,NaN,NaN,1,18.0,2012.0,"Feb,May,Aug,Nov"
250,251,a,c,340.0,NaN,NaN,0,NaN,NaN,NaN
251,252,d,c,22330.0,NaN,NaN,1,5.0,2010.0,"Feb,May,Aug,Nov"
252,253,a,c,250.0,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"
253,254,d,a,330.0,3.0,2008.0,1,1.0,2012.0,"Mar,Jun,Sept,Dec"
254,255,c,c,4630.0,3.0,2011.0,1,35.0,2011.0,"Feb,May,Aug,Nov"
255,256,a,c,80.0,9.0,2005.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
256,257,a,a,420.0,12.0,2012.0,0,NaN,NaN,NaN
257,258,a,a,27190.0,7.0,2010.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
258,259,b,b,210.0,NaN,NaN,0,NaN,NaN,NaN
259,260,a,a,540.0,10.0,2011.0,0,NaN,NaN,NaN
260,261,d,c,15340.0,4.0,2015.0,1,39.0,2009.0,"Jan,Apr,Jul,Oct"
261,262,b,a,1180.0,5.0,2013.0,0,NaN,NaN,NaN
262,263,a,c,1140.0,5.0,2013.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
263,264,a,a,180.0,3.0,2014.0,0,NaN,NaN,NaN
264,265,a,a,4580.0,NaN,NaN,1,14.0,2015.0,"Jan,Apr,Jul,Oct"
265,266,a,c,360.0,3.0,2014.0,1,9.0,2011.0,"Mar,Jun,Sept,Dec"
266,267,c,a,2460.0,1.0,2012.0,0,NaN,NaN,NaN
267,268,a,a,4520.0,2.0,2014.0,0,NaN,NaN,NaN
268,269,a,c,60.0,6.0,2015.0,0,NaN,NaN,NaN
269,270,a,a,1450.0,7.0,2014.0,0,NaN,NaN,NaN
270,271,a,a,420.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
271,272,a,a,16180.0,7.0,2003.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
272,273,a,c,8480.0,NaN,NaN,0,NaN,NaN,NaN
273,274,b,b,3640.0,NaN,NaN,1,10.0,2013.0,"Jan,Apr,Jul,Oct"
274,275,d,a,300.0,5.0,2014.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
275,276,a,a,2960.0,10.0,2014.0,1,36.0,2013.0,"Mar,Jun,Sept,Dec"
276,277,d,c,7840.0,NaN,NaN,1,31.0,2009.0,"Feb,May,Aug,Nov"
277,278,a,c,9260.0,2.0,2010.0,0,NaN,NaN,NaN
278,279,d,c,2320.0,NaN,NaN,1,40.0,2012.0,"Jan,Apr,Jul,Oct"
279,280,d,c,18640.0,9.0,2013.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
280,281,d,c,6970.0,9.0,2011.0,0,NaN,NaN,NaN
281,282,a,a,1220.0,12.0,2010.0,0,NaN,NaN,NaN
282,283,a,a,2260.0,NaN,NaN,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
283,284,d,a,1290.0,NaN,NaN,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
284,285,a,a,2410.0,NaN,NaN,0,NaN,NaN,NaN
285,286,a,a,1460.0,4.0,2015.0,0,NaN,NaN,NaN
286,287,c,a,2740.0,5.0,2009.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
287,288,d,a,800.0,NaN,NaN,1,14.0,2011.0,"Mar,Jun,Sept,Dec"
288,289,d,a,6540.0,12.0,2007.0,0,NaN,NaN,NaN
289,290,a,a,4150.0,5.0,2001.0,0,NaN,NaN,NaN
290,291,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
291,292,a,a,1100.0,6.0,2009.0,0,NaN,NaN,NaN
292,293,c,c,140.0,11.0,2007.0,0,NaN,NaN,NaN
293,294,a,a,3150.0,5.0,2005.0,0,NaN,NaN,NaN
294,295,a,a,210.0,11.0,2000.0,1,36.0,2013.0,"Mar,Jun,Sept,Dec"
295,296,a,a,9580.0,5.0,2007.0,1,45.0,2014.0,"Feb,May,Aug,Nov"
296,297,a,a,2300.0,9.0,2010.0,0,NaN,NaN,NaN
297,298,d,a,19840.0,7.0,2009.0,0,NaN,NaN,NaN
298,299,d,c,38630.0,9.0,2012.0,0,NaN,NaN,NaN
299,300,a,c,120.0,4.0,2009.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
300,301,a,c,4510.0,3.0,2015.0,0,NaN,NaN,NaN
301,302,d,c,2190.0,12.0,2007.0,1,9.0,2011.0,"Mar,Jun,Sept,Dec"
302,303,a,a,15430.0,11.0,2012.0,1,18.0,2011.0,"Feb,May,Aug,Nov"
303,304,a,a,1950.0,7.0,2015.0,0,NaN,NaN,NaN
304,305,c,c,2470.0,2.0,2005.0,1,31.0,2013.0,"Mar,Jun,Sept,Dec"
305,306,a,a,5100.0,4.0,2007.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
306,307,a,a,18660.0,9.0,2002.0,0,NaN,NaN,NaN
307,308,a,a,1070.0,12.0,2006.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
308,309,d,a,8740.0,NaN,NaN,1,37.0,2009.0,"Feb,May,Aug,Nov"
309,310,a,c,2290.0,NaN,NaN,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
310,311,a,c,680.0,7.0,2005.0,0,NaN,NaN,NaN
311,312,d,a,11300.0,3.0,2012.0,0,NaN,NaN,NaN
312,313,d,c,14160.0,NaN,NaN,0,NaN,NaN,NaN
313,314,a,a,3560.0,10.0,2001.0,1,31.0,2013.0,"Feb,May,Aug,Nov"
314,315,a,c,38710.0,4.0,2013.0,0,NaN,NaN,NaN
315,316,d,a,9000.0,8.0,2001.0,0,NaN,NaN,NaN
316,317,d,a,3140.0,7.0,2013.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
317,318,d,c,32330.0,3.0,2014.0,0,NaN,NaN,NaN
318,319,a,c,570.0,9.0,2012.0,1,27.0,2012.0,"Mar,Jun,Sept,Dec"
319,320,a,c,210.0,9.0,2012.0,0,NaN,NaN,NaN
320,321,c,c,8140.0,11.0,2013.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
321,322,a,a,17500.0,4.0,2001.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
322,323,d,c,8400.0,4.0,2012.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
323,324,a,a,13140.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
324,325,a,c,350.0,3.0,2011.0,1,22.0,2011.0,"Feb,May,Aug,Nov"
325,326,d,a,10070.0,5.0,2015.0,1,31.0,2013.0,"Feb,May,Aug,Nov"
326,327,c,c,1390.0,12.0,2004.0,0,NaN,NaN,NaN
327,328,a,a,3130.0,7.0,2002.0,0,NaN,NaN,NaN
328,329,a,a,1310.0,6.0,1990.0,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
329,330,a,c,370.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
330,331,a,c,670.0,NaN,NaN,1,14.0,2015.0,"Jan,Apr,Jul,Oct"
331,332,a,a,1840.0,3.0,2006.0,0,NaN,NaN,NaN
332,333,a,c,3720.0,2.0,2010.0,0,NaN,NaN,NaN
333,334,d,c,4040.0,8.0,2008.0,1,18.0,2013.0,"Mar,Jun,Sept,Dec"
334,335,b,a,90.0,NaN,NaN,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
335,336,a,a,190.0,7.0,2014.0,0,NaN,NaN,NaN
336,337,d,c,10600.0,7.0,2005.0,1,45.0,2014.0,"Feb,May,Aug,Nov"
337,338,a,c,1590.0,NaN,NaN,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
338,339,a,c,2280.0,NaN,NaN,1,10.0,2013.0,"Mar,Jun,Sept,Dec"
339,340,a,c,8080.0,NaN,NaN,0,NaN,NaN,NaN
340,341,a,a,190.0,9.0,2011.0,0,NaN,NaN,NaN
341,342,d,c,15770.0,NaN,NaN,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
342,343,d,a,18650.0,4.0,2004.0,1,14.0,2014.0,"Jan,Apr,Jul,Oct"
343,344,a,c,300.0,4.0,2011.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
344,345,a,a,120.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
345,346,a,c,8090.0,NaN,NaN,0,NaN,NaN,NaN
346,347,d,c,9360.0,7.0,2013.0,1,22.0,2012.0,"Mar,Jun,Sept,Dec"
347,348,a,a,16490.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
348,349,c,c,1490.0,4.0,2009.0,0,NaN,NaN,NaN
349,350,d,a,8880.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
350,351,a,a,5290.0,11.0,2012.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
351,352,d,c,6360.0,NaN,NaN,1,40.0,2012.0,"Mar,Jun,Sept,Dec"
352,353,b,b,900.0,NaN,NaN,1,14.0,2013.0,"Feb,May,Aug,Nov"
353,354,d,c,1500.0,10.0,2005.0,0,NaN,NaN,NaN
354,355,a,c,9720.0,8.0,2013.0,0,NaN,NaN,NaN
355,356,d,c,8970.0,12.0,2007.0,1,22.0,2012.0,"Feb,May,Aug,Nov"
356,357,a,a,2060.0,10.0,2008.0,0,NaN,NaN,NaN
357,358,a,a,2890.0,10.0,2003.0,0,NaN,NaN,NaN
358,359,d,c,4370.0,NaN,NaN,0,NaN,NaN,NaN
359,360,a,a,2040.0,6.0,2007.0,0,NaN,NaN,NaN
360,361,c,c,4490.0,5.0,2014.0,1,5.0,2013.0,"Feb,May,Aug,Nov"
361,362,c,c,340.0,NaN,NaN,0,NaN,NaN,NaN
362,363,a,a,250.0,9.0,2009.0,0,NaN,NaN,NaN
363,364,a,c,13620.0,NaN,NaN,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
364,365,c,a,2410.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
365,366,d,c,6470.0,12.0,2004.0,0,NaN,NaN,NaN
366,367,d,c,2640.0,9.0,2012.0,0,NaN,NaN,NaN
367,368,d,c,1450.0,4.0,2005.0,1,45.0,2009.0,"Feb,May,Aug,Nov"
368,369,d,c,5870.0,4.0,2014.0,0,NaN,NaN,NaN
369,370,d,a,8250.0,10.0,2000.0,1,31.0,2009.0,"Jan,Apr,Jul,Oct"
370,371,d,c,1970.0,7.0,2009.0,1,45.0,2014.0,"Feb,May,Aug,Nov"
371,372,d,c,4880.0,8.0,2010.0,1,18.0,2014.0,"Jan,Apr,Jul,Oct"
372,373,d,c,11120.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
373,374,a,a,1150.0,9.0,2007.0,0,NaN,NaN,NaN
374,375,a,c,15710.0,2.0,2013.0,1,37.0,2009.0,"Jan,Apr,Jul,Oct"
375,376,a,a,160.0,8.0,2012.0,0,NaN,NaN,NaN
376,377,a,c,100.0,6.0,2010.0,1,18.0,2010.0,"Feb,May,Aug,Nov"
377,378,a,c,2140.0,8.0,2012.0,0,NaN,NaN,NaN
378,379,d,a,6630.0,NaN,NaN,0,NaN,NaN,NaN
379,380,a,a,2240.0,5.0,2013.0,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
380,381,a,a,1800.0,11.0,2006.0,1,5.0,2013.0,"Feb,May,Aug,Nov"

In [51]:
df_population_data.head() #5 primeiras linhas

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [52]:
df_population_data.head(10) # as 10 primeiras linhas

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN

In [53]:
df_population_data.tail(10) #as 10 Ãºltimas linhas

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1105,1106,a,c,5330.0,9.0,2011.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1106,1107,a,a,1400.0,6.0,2012.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
1107,1108,a,a,540.0,4.0,2004.0,0,NaN,NaN,NaN
1108,1109,c,a,3490.0,4.0,2011.0,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
1109,1110,c,c,900.0,9.0,2010.0,0,NaN,NaN,NaN
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [55]:
df_population_data.sample(10) # 10 itens aleatÃ³rios

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
857,858,a,a,3370.0,12.0,2008.0,1,40.0,2014.0,"Jan,Apr,Jul,Oct"
79,80,d,a,7910.0,NaN,NaN,0,NaN,NaN,NaN
843,844,a,a,2030.0,9.0,2012.0,1,18.0,2011.0,"Feb,May,Aug,Nov"
40,41,d,c,1180.0,NaN,NaN,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
800,801,d,a,48330.0,4.0,2013.0,0,NaN,NaN,NaN
574,575,a,a,960.0,5.0,2008.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
869,870,a,a,780.0,4.0,2009.0,0,NaN,NaN,NaN
530,531,a,c,4030.0,NaN,NaN,0,NaN,NaN,NaN
577,578,d,a,12700.0,4.0,2013.0,0,NaN,NaN,NaN
822,823,a,c,16210.0,11.0,2010.0,0,NaN,NaN,NaN

In [56]:
df_population_data.info() #informaÃ§Ãµes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [57]:
df_population_data.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [59]:
df_population_data.describe().round(0)

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.0,1112.0,761.0,761.0,1115.0,571.0,571.0
mean,558.0,5405.0,7.0,2009.0,1.0,24.0,2012.0
std,322.0,7663.0,3.0,6.0,1.0,14.0,2.0
min,1.0,20.0,1.0,1900.0,0.0,1.0,2009.0
25%,280.0,718.0,4.0,2006.0,0.0,13.0,2011.0
50%,558.0,2325.0,8.0,2010.0,1.0,22.0,2012.0
75%,836.0,6882.0,10.0,2013.0,1.0,37.0,2013.0
max,1115.0,75860.0,12.0,2015.0,1.0,50.0,2015.0